---
- hosts: prod_gb

  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - common
    - role: geerlingguy.nginx
      tags: nginx
    - role: geerlingguy.php
      tags: php
    - role: geerlingguy.mysql
      tags: mysql
    - role: wordpress
      tags: 
        - app
        - wordpress

  tasks:

    - name: Enabling http for zone public
      ansible.posix.firewalld:
        zone: public
        service: http
        state: enabled
        permanent: true
        immediate: true
      when:
        - ansible_os_family == "RedHat"
